apiVersion: monitoring.coreos.com/v1alpha1
kind: ServiceMonitor
metadata:
  name: "dns-metrics-{{ .Release.Name }}"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app: prometheus
    prometheus: us-west-2
    component: "{{ printf "%s-dns-metrics" .Release.Name | trunc 24 }}"
spec:
  jobLabel: "dns-monitor"
  selector:
    matchLabels:
      component: "{{ printf "%s-dns-metrics" .Release.Name | trunc 24 }}"
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: dns-metrics
    interval: 15s
    scheme: http
