apiVersion: v1
kind: Service
metadata:
  name: "dns-metrics-{{ .Release.Name }}"
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: "{{ printf "%s-dns-metrics" .Release.Name | trunc 24 }}"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
  selector:
    component: "{{ printf "%s-dns-metrics" .Release.Name | trunc 24 }}"
